In [13]:
import numpy as np

T = np.array([1, 0, 0, 1])
P = np.array([1, 0, 1, 1])

T_ = np.array(T) & (~np.array(P) & 1)
P_ = np.array(P) & (~np.array(T) & 1)

if all(T_==P_):
  M = np.diag(T)
  CR = np.diag(T)
  CP = np.diag(T)
        
if all(T_== 0) and any(P_== 1):
  M = (np.outer(T, P_) + np.sum(T)*np.diag(T))/np.sum(P)
  CR = np.diag(T)
  CP = np.outer(T,P_)/np.sum(T) + np.diag(T)

if all(P_== 0) and any(T_ == 1):
  M = np.outer(T_,P)/np.sum(P) + np.diag(P)
  CR = np.outer(T_,P)/np.sum(P) + np.diag(P)
  CP = np.diag(P)

if any(T_== 1) and any(P_== 1):
  M = np.outer(T_, P_)/np.sum(P_) + np.diag(T&P)
  CR = np.diag(T&P) + np.outer(T_,P_)/np.sum(P_)
  CP = np.diag(T&P) + np.outer(T_,P_)/np.sum(T_)

print(M)
print(CR)
print(CP)

[[0.66666667 0.         0.33333333 0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.33333333 0.66666667]]
[[1 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 1]]
[[1.  0.  0.5 0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.5 1. ]]


In [14]:
T = np.array([1, 1, 0, 0])
P = np.array([1, 0, 0, 0])

T_ = np.array(T) & (~np.array(P) & 1)
P_ = np.array(P) & (~np.array(T) & 1)

if all(T_==P_):
  M = np.diag(T)
  CR = np.diag(T)
  CP = np.diag(T)
        
if all(T_== 0) and any(P_== 1):
  M = (np.outer(T, P_) + np.sum(T)*np.diag(T))/np.sum(P)
  CR = np.diag(T)
  CP = np.outer(T,P_)/np.sum(T) + np.diag(T)

if all(P_== 0) and any(T_ == 1):
  M = np.outer(T_,P)/np.sum(P) + np.diag(P)
  CR = np.outer(T_,P)/np.sum(P) + np.diag(P)
  CP = np.diag(P)

if any(T_== 1) and any(P_== 1):
  M = np.outer(T_, P_)/np.sum(P_) + np.diag(T&P)
  CR = np.diag(T&P) + np.outer(T_,P_)/np.sum(P_)
  CP = np.diag(T&P) + np.outer(T_,P_)/np.sum(T_)

print(M)
print(CR)
print(CP)

[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
